name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Проверка кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Восстановление зависимостей
    - name: Restore dependencies
      run: dotnet restore

    # Сборка проекта
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Запуск тестов
    - name: Test
      run: dotnet test --no-build --configuration Release
