name: .NET CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Проверка кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Восстановление зависимостей
    - name: Restore dependencies
      run: dotnet restore

    # Сборка проекта
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Запуск тестов
    - name: Test
      run: dotnet test --no-build --configuration Release

    # Логин в DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Сборка и пуш Docker-образа
    - name: Build and push Docker image
      run: |
        docker build -t mydockerhubusername/laba1marta:latest .
        docker push mydockerhubusername/laba1marta:latest

    # Деплой и запуск контейнера (если необходимо)
    - name: Deploy to local Docker container (optional)
      run: |
        docker stop laba1marta || true
        docker rm laba1marta || true
        docker run -d --name laba1marta -p 8080:80 mydockerhubusername/laba1marta:latest
